### ISSUE TITLE
Regole di implementazione, estensione e utilizzo del pacchetto @ v2.0.0

### ISSUE THREAD

**Issue by alessiosantangelo** [primait/pyxis-npm#35]
- [ ] I componenti devono essere indipendenti, predittivi, e agnostici rispetto alla loro posizione in pagina e/o ai fratelli
- [ ] I componenti  devono poter lavorare solo sul loro scope interno (no margin o modificatori esterni alla loro root). Position, transform, sono considerate proprietà scoped (non abusarne).
- [ ] Il modale deve sempre includere un overlay
- [ ] Nel caso in cui si debba applicare a un elemento del design system un modificatore non ancora presente in Pyxis, bisogna: classare l'elemento secondo il suo significato per l'end-user o di design mantenendo BEM e RIMUOVENDO la nomenclatura atomica sulle customizzazioni della pagina
- [ ] Tutto ciò che è configurabile per le app esterne DEVE avere una mappa di configurazione.
- [ ] Tutte le mappe di configurazioni DEVONO essere definite all'interno del file variables.  
- [ ] Implementare visual regression su Pyxis-npm
- [ ] I componenti devono avere documentazione, use cases ed esempi di utilizzo
- [ ] Bisogna integrare un linter

**Comment by damjack** [comment]
A questo punto mi sorge una domanda: che differenza esiste tra COMPONENTI DI LAYOUT `l-` e invece ATOMI `a-`, MOLECOLE `m-` e ORGANISMI `o-`?

**Comment by alessiosantangelo** [comment]
@damjack infatti non tutti sono convinti di questa feature. Motivo per cui è un candidato per le prossime valutazioni

**Comment by damjack** [comment]
Sempre rimanendo sulla scia di quanto hai scritto avrei come proposte:

- [ ] conversione automatica da PX a REM e utilizzo di moltiplicatori per le spaziature
- [ ] introduzione di MIXINS parlati per la generazione diretta di regole CSS (es: `+padding(top, right, bottom, left)`, `+absolute(top, right, bottom, left)`, `+line-font(fontSize, lineHeight)`)

Con la prima abbiamo cosi la possibilità di avere delle grafiche coordinate e puntuali con font-size e line-height definiti e le spaziature diventerebbero una costante con moltiplicatore (es. spaziatura di base 10px che poi tramite MIXINS si possa utilizzare tipo `baseSpace * MOLTIPLICATORE`)

Con la seconda ci viene più leggibile il codice e le classi diventano più snelle ed inoltre si rischia meno che si utilizzino parti troppo custom

**Comment by alessiosantangelo** [comment]
@damjack ok tempo fa avevamo queste opzioni ma le abbiamo usate sempre un po' male. Le avevamo rimosse per questo. Possiamo reintrodurle però scrivendole per bene
